import React from 'react';
import { Footer } from '@/components/Footer';

export default function TermsPage() {
    return (
        <div className="min-h-screen bg-slate-50 font-sans">
            <div className="py-20 px-4 md:px-8">
                <div className="max-w-4xl mx-auto bg-white p-8 md:p-12 rounded-[2.5rem] shadow-xl border border-slate-100">
                    <h1 className="text-3xl md:text-4xl font-black text-[#00703C] mb-8 border-b border-slate-100 pb-4">Terms and Conditions</h1>

                    <div className="space-y-6 text-slate-600 leading-relaxed text-sm md:text-base">
                        <p className="border-l-4 border-yellow-400 pl-4 bg-yellow-50 p-4 rounded-r-xl">
                            This document is an electronic record as per the Information Technology Act, 2000, its amendments from time to time and applicable regulations and the amended provisions relating to electronic records in various enactments amended by the Information Technology Act, 2000. The document is generated by a computer system and does not require any physical or digital signatures.
                        </p>

                        <p>
                            Before registering, accessing or using the services of DEVARAMANE EVENTS AND INDUSTRIES (www.devaramane.com) carefully read the terms and conditions (explained below). THE TERMS AND CONDITIONS ARE A LEGAL AGREEMENT BETWEEN YOU AND DEVARAMANE EVENTS AND INDUSTRIES ("DEVARAMANE EVENTS"), CHINNIGA, JANNAPURA VILLAGE AND POST, GONIBEEDU HOBALI, MUDIGERE THALUK, CHIKKAMAGALURE DISTRICT, KARNATAKA, INDIA 577132 subject to the terms and conditions set forth below. YOU AGREE AND ACKNOWLEDGE THAT YOU HAVE READ. IF YOU DO NOT AGREE TO THESE TERMS AND CONDITIONS OR DO NOT WANT TO BE BOUND BY THESE TERMS AND CONDITIONS, YOU MAY NOT USE THE SERVICES AND/OR IMMEDIATELY TERMINATE THE SERVICES AND/OR UNINSTALL THE MOBILE APPLICATION.
                        </p>

                        <p>
                            We may amend the Terms and Conditions at any time by posting an updated version on the DEVARAMANE Website(s) and DEVARAMANE Application(s). An updated version of the Terms of Service will be effective immediately upon posting. It is your responsibility to review these Terms of Use periodically for updates and changes. Your continued use of the DEVARAMANE EVENTS Application after the posting of changes will mean that you accept and agree to the revisions, including additional terms or removal of portions of these Terms, modifications, etc. As long as you comply with these Terms of Use, we grant you a personal, non-exclusive, non-transferable, limited privilege to access and obtain the Services.
                        </p>

                        <p>
                            USING THE DEVARAMANE EVENTS (DEVARAMANE) APPLICATION INDICATES YOUR AGREEMENT TO ALL TERMS AND CONDITIONS UNDER THESE TERMS OF USE, SO PLEASE READ THE TERMS OF USE CAREFULLY BEFORE PROCEEDING. By implicitly or expressly accepting these Terms of Use, you acknowledge and agree to be bound by the Privacy Policy Terms (including but not limited to the Privacy Policy) on the DEVARAMANE website(s) and DEVARAMANE application(s) as amended from time to time.
                        </p>

                        <h2 className="text-xl font-bold text-slate-900 mt-8 mb-4">Eligibility</h2>
                        <p>BY ACCESSING THE DEVARAMANE EVENTS MANAGEMENT AND SERVICE AND DEVARAMANE PLATFORMS, YOU REPRESENT THAT:-</p>
                        <ul className="list-disc pl-5 space-y-2">
                            <li>You are 18 years of age or older;</li>
                            <li>You are capable of entering into a contract/legal agreement;</li>
                            <li>You have the right, authority and capacity to enter into this Agreement subject to all provisions of the "Terms of Use" of DEVARAMANE EVENTS AND INDUSTRIES Services.</li>
                            <li>You are not restricted or legally prohibited from accessing or using the services of DEVARAMANE EVENTS AND INDUSTRIES or DEVARAMANE entities under the laws of India.</li>
                            <li>You are not impersonating any person or entity or misrepresenting your age or affiliation with any person or entity. DEVARAMANE EVENTS AND INDUSTRIES and DEVARAMANE entities shall reserve the right to terminate your agreement to use the DEVARAMANE PLATFORM in case of any misrepresentation of the above mentioned conditions.</li>
                            <li>Mandatory information and officially valid document(s) Address Proof Identify Document details of documents mentioned by you are true and correct and belong to you.</li>
                            <li>DEVARAMANE EVENTS AND INDUSTRIES (DEVARAMANE) Company cannot have more than one registration and one person cannot get more than one ID and no amendment including transfer of ID.</li>
                        </ul>

                        <h2 className="text-xl font-bold text-slate-900 mt-8 mb-4">Sign up / Registration</h2>
                        <p>
                            To use the full spectrum of DEVARAMANE EVENTS AND INDUSTRIES services, you need to register on the DEVARAMANE application and provide us with accurate and complete information. You are required to update your accounts, KYC details and contact information completely and at all times.
                        </p>

                        <h2 className="text-xl font-bold text-slate-900 mt-8 mb-4">Self Declaration Before Registration</h2>
                        <ul className="list-disc pl-5 space-y-2">
                            <li>I am registered and understand to be bound by all the rules and regulations of the company.</li>
                            <li>I self-certify that I will not cheat, give false information or cheat in the name of the company or any person in the company.</li>
                            <li>I will respect the people of the company and work sincerely for the growth of the company.</li>
                            <li>In case of negligence or mishap by me to the company DEVARAMANE EVENTS AND INDUSTRIES, I myself shall be bound and agree to bear the loss caused to the company in such case.</li>
                        </ul>
                    </div>
                </div>
            </div>
            <Footer />
        </div>
    );
}
